### ISSUE TITLE
Add Grafana to the deployment scripts

### ISSUE THREAD

**Issue by geoffreymantel** [scp756-221/term-project-babyshark#2]
To enable metrics dashboards, the grafana tool will need to be deployed to our cluster.

**Comment by geoffreymantel** [comment]
Read this for details: https://scp756-221.github.io/course-site//#/g1-graf/page?embedded=true&hidegitlink=true

**Comment by adhavan-sfu** [comment]
Added the necessary scripts back to repo for grafana. It's up and running. Waiting on gatling setup to test the dashboard.

**Comment by geoffreymantel** [comment]
Looks great! Thanks @adhavan-sfu
