### ISSUE TITLE
Term Project Report

### ISSUE THREAD

**Issue by geoffreymantel** [scp756-221/term-project-babyshark#27]
As per the outline: https://scp756-221.github.io/course-site//#/tprj/page?embedded=true&hidegitlink=true

**Comment by geoffreymantel** [comment]
Just start it and we can all fill out collaboratively.

**Comment by dugongzzz** [comment]
https://docs.google.com/document/d/1MAc69yrZOANw8l1XKgwIPSABYMOtHCR7kF5VyLW1HsE/edit?usp=sharing
